top_banners :
  - camp
  - main
profile_placeholder :
  "例）こんにちは☆ ご覧いただきありがとうございます！
  かわいいものやきれいめオフィスカジュアル中心に出品しています。
  服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、
  商品や発送方法などご質問がありましたらお気軽にどうぞ♪"
credit_card_logos :
  - 'visa.svg'
  - 'master-card.svg'
  - 'saison-card.svg'
  - 'jcb.svg'
  - 'american_express.svg'
  - 'dinersclub.svg'
  - 'discover.svg'
prefecture:
  - '北海道'
  - '青森県'
  - '岩手県'
  - '宮城県'
  - '秋田県'
  - '山形県'
  - '福島県'
  - '茨城県'
  - '栃木県'
  - '群馬県'
  - '埼玉県'
  - '千葉県'
  - '東京都'
  - '神奈川県'
  - '新潟県'
  - '富山県'
  - '石川県'
  - '福井県'
  - '山梨県'
  - '長野県'
  - '岐阜県'
  - '静岡県'
  - '愛知県'
  - '三重県'
  - '滋賀県'
  - '京都府'
  - '大阪府'
  - '兵庫県'
  - '奈良県'
  - '和歌山県'
  - '鳥取県'
  - '島根県'
  - '岡山県'
  - '広島県'
  - '山口県'
  - '徳島県'
  - '香川県'
  - '愛媛県'
  - '高知県'
  - '福岡県'
  - '佐賀県'
  - '長崎県'
  - '熊本県'
  - '大分県'
  - '宮崎県'
  - '鹿児島県'
  - '沖縄県'
  - '未定'
item_size :
  - 'XXS以下'
  - 'XS(SS)'
  - 'S'
  - 'M'
  - 'L'
  - 'XL(LL)'
  - '2XL(3LL)'
  - '3XL(4LL)'
  - '4XL(5LL)'
  - 'FREE SIZE'
item_state :
  - '新品、未使用'
  - '未使用に近い'
  - '目立った傷や汚れなし'
  - 'やや傷や汚れあり'
  - '傷や汚れあり'
  - '全体的に状態が悪い'
delivery_charge :
  - '着払い（購入者負担）'
  - '送料込み（出品者負担）'
shipping_fee :
  - '送料別'
  - '送料込み'
delivery_way :
  - '未定'
  - 'ゆうメール'
  - 'ゆうパック'
  - 'クロネコヤマト'
  - 'らくらくメルカリ便'
  - 'レターパック'
  - '普通郵便（定形、定形外）'
  - 'クリックポスト'
  - 'ゆうパケット'
delivery_way_number_for_buyer : 4
delivery_time :
  - '1~2日で発送'
  - '2~3日で発送'
  - '4~7日で発送'
